HW1
Space27/JavaBackendAutumn pull request #1
Opened 2023-10-06 17:41 UTC by Space27

2023-10-08 14:47 UTC, Stasik371 commented
Настрой squash коммитов при пуше в мастер, если еще не сделал этого)

2023-10-08 14:48 UTC, Stasik371 commented on README.md
> +![Build Status](https://github.com/Space27/Tinkoff_Edu_HW_LokosovD/actions/workflows/build.yml/badge.svg)
Лайк за бадж)

2023-10-08 14:48 UTC, Stasik371 commented on src/main/java/edu/hw1/Task0.java
> +    private final static org.apache.logging.log4j.Logger LOGGER = LogManager.getLogger();
Давай пропустим строку. Тут и везде

2023-10-08 15:50 UTC, Stasik371 requested changes

2023-10-08 15:50 UTC, Stasik371 commented on src/main/java/edu/hw1/Task1.java
> +        if (time == null || !time.matches("\\d{2,}:\\d{2}")) {
Круто, что знаешь регулярки)

Но на будущее, они не всегда подходят, потому что их очень сложно читать

2023-10-08 15:50 UTC, Stasik371 commented on src/main/java/edu/hw1/Task1.java
> +        final int secondsInMinute = 60;
Думаю, что можно в константу вынести)

2023-10-08 15:50 UTC, Stasik371 commented on src/main/java/edu/hw1/Task0.java
> +    private final static org.apache.logging.log4j.Logger LOGGER = LogManager.getLogger();
```suggestion
    private static final Logger LOGGER = LogManager.getLogger();
```

Просто импортни)

2023-10-08 15:50 UTC, Stasik371 commented on src/main/java/edu/hw1/Task2.java
> +        /* ещё можно было бы использовать десятичный логарифм по модулю числа (не учитывая 0) */
лайк)

2023-10-08 15:50 UTC, Stasik371 commented on src/main/java/edu/hw1/Task3.java
> +        for (var i : arr) {
Иногда лучше стараться избегать var, это не панацея) Тоже на будущее

2023-10-08 15:50 UTC, Stasik371 commented on src/main/java/edu/hw1/Task3.java
> +        /* вместо написанных методов можно было использовать встроенные методы класса Arrays */
Лайк, что знаешь) Только комменты в коде лучше не закидывать в мастер, удали плиз)

2023-10-08 15:50 UTC, Stasik371 commented on src/main/java/edu/hw1/Task6.java
> +        final int kConst = 6174;
Думаю такое точно нужно в константу вынести)

2023-10-08 15:50 UTC, Stasik371 commented on src/main/java/edu/hw1/Task6.java
> +            return 0;
как-будто 0 в данном случае выдастся и при 6174. Может будем -1 возвращать?

2023-10-08 15:50 UTC, Stasik371 commented on src/main/java/edu/hw1/Task6.java
> +        for (int i = 0; i < arr.length / 2; ++i) {
Жесть ты математик)

2023-10-08 15:50 UTC, Stasik371 commented on src/main/java/edu/hw1/Task7.java
> +    public static int rotateRight(int inputNumber, int inputShift) throws IllegalAccessError {
точно  `IllegalAccessError` ? Ты вроде немного другое бросаешь)

2023-10-08 15:50 UTC, Stasik371 commented on src/main/java/edu/hw1/Task7.java
> +            throw new IllegalArgumentException();
Тут можно в конструктор передать сообщение, чтоб было видно: что пошло не так)

2023-10-08 15:50 UTC, Stasik371 commented on src/main/java/edu/hw1/Task7.java
> +        int tmpMask = (int) Math.pow(2, shift) - 1; /* создаётся маска типа 0..01..1 из shift 1 */
Как говорил один мудрец:

Хороший код тот, который не нуждается в комментировании

2023-10-08 15:50 UTC, Stasik371 commented on src/test/java/edu/hw1/Task1Test.java
> +    @DisplayName("Простая длина видео")
А чем Простая длина видео отличается от обычной длины видео?)

2023-10-08 15:50 UTC, Stasik371 commented on src/test/java/edu/hw1/Task1Test.java
> +    void simpleVL() {
А что такое VL? Давай лучше напишем по-человечески)


У нас в команде есть такой паттерн:

НазваниеМетода_ShouldЧто-тоДелать

Например здесь

minutesToSeconds_shouldConvertIfDataIsValid


А так можешь поиграться, но главное, чтоб метод с аннотацией @Test передавал суть того, какой Тест-Кейс тестирует)

2023-10-08 15:50 UTC, Stasik371 commented on src/test/java/edu/hw1/Task1Test.java
> +}
Лайк, очень хорошие ТК)

2023-10-08 15:50 UTC, Stasik371 commented on src/test/java/edu/hw1/Task1Test.java
> +        // given
Давай уж, если начал, то везде givenWhenThen писать)

2023-10-08 15:50 UTC, Stasik371 commented on src/test/java/edu/hw1/Task3Test.java
> +        int[] firstArray = {1, 2};
Можно кстати попробовать параметризированные тесты писать) 

https://www.baeldung.com/parameterized-tests-junit-5 

тут хорошо написано. Можно например передавать 2 массива и результат.


Такое можно провернуть почти со всеми методами, будет меньше кода)

2023-10-08 15:50 UTC, Stasik371 commented on src/test/java/edu/hw1/Task4Test.java
> +    @DisplayName("Строки нет")
Лучше написать Строка null, это все-таки немного разное)

2023-10-08 15:50 UTC, Stasik371 commented on src/test/java/edu/hw1/Task5Test.java
> +        int number = 979710; /* 979710 -> 16161 */
Давай такой коммент везде закинем. Потому что не очень понятно, что проверяют эти тесты, они ничем не подкреплены( Это конечно задание такое, поэтому так делать-скорее исключение.

2023-10-08 15:50 UTC, Stasik371 commented on src/test/java/edu/hw1/Task5Test.java
> +}
Давай в таких задачках всегда 0 прокидывать в тестах

2023-10-08 15:50 UTC, Stasik371 commented on src/test/java/edu/hw1/Task6Test.java
> +            .isEqualTo(0);
Тут на -1 не забудь поправить)

2023-10-08 15:50 UTC, Stasik371 commented on src/test/java/edu/hw1/Task7Test.java
> +    void shiftLikeLenRightNum() {
лайк!

2023-10-08 16:08 UTC, Space27 commented on src/main/java/edu/hw1/Task7.java
> +        int tmpMask = (int) Math.pow(2, shift) - 1; /* создаётся маска типа 0..01..1 из shift 1 */
Просто я не знаю, как сделать создание маски более понятным за одну строку (есть вариант сделать цикл, где к маске будет прибавляться 1 и делаться побитовый сдвиг, но строк больше). А так можно через строки сделать, но как будто нетрушно)

2023-10-08 19:59 UTC, Space27 commented on src/main/java/edu/hw1/Task1.java
> +        if (time == null || !time.matches("\\d{2,}:\\d{2}")) {
Просто нужно было уменьшить кол-во return в данной функции, поэтому пришлось бы делать валидатор. А я и подумал, зачем делать мудреный валидатор (который при этом будет делать похожие действия, что и сама функция), если гораздо легче написать простенькую регулярку, которая будет делать то же самое за меньшее число строк кода.
А в каких случаях неуместно использовать их? Просто по идее (да и в ВУЗе нам рассказывали), что их удобно использовать для проверки формата номеров, паролей, сигнатур функций и т.д., хотя там они порой очень сложные получаются.

2023-10-08 22:11 UTC, Space27 commented on src/test/java/edu/hw1/Task3Test.java
> +        int[] firstArray = {1, 2};
Спасибо за наводку. Очень классно облегчает написание однотипных тестов для разных подслучаев.

2023-10-10 19:12 UTC, Stasik371 commented on src/main/java/edu/hw1/Task1.java
> +        if (time == null || !time.matches("\\d{2,}:\\d{2}")) {
В данном контексте норм, она еще тут простая, так что наоборот красавчик) Я скорее на будущее говорил, что это не серебряная пуля.
 
1 раз я встретил нечто такое и захотелось глаза выколоть)

`/^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i`

Вот такую уже неуместно использовать, это не то, что неудобно, это больно)

2023-10-10 19:30 UTC, Stasik371 commented on src/main/java/edu/hw1/Task7.java
> +        int tmpMask = (int) Math.pow(2, shift) - 1; /* создаётся маска типа 0..01..1 из shift 1 */
На самом деле можно вынести в отдельный метод и как-нибудь его назвать красиво, будет прикольнее. Ты посмотришь на название метода и в 2 словах поймешь что там за приколы с битиками делаются)

2023-10-10 19:31 UTC, Stasik371 commented on src/main/java/edu/hw1/Task6.java
> +        if (number == K_CONST) {
Вообще, предположительно, это не корнерКейс, а общий случай) Но такой иф имеет место быть

2023-10-10 19:33 UTC, Stasik371 commented on src/test/java/edu/hw1/Task1Test.java
> +    @CsvSource({"1378:59, 82739", "12:43, 763", "10:00, 600", "00:59, 59"})
Еще есть крутая аннотация @MethodSource, тоже очень помогает) Например можно передать входной параметр и ожидаемый результат через Arguments.of()

 https://www.baeldung.com/parameterized-tests-junit-5

2023-10-10 19:34 UTC, Stasik371 approved these changes

2023-10-10 19:35 UTC, Stasik371 commented
![image](https://github.com/Space27/Tinkoff_Edu_HW_LokosovD/assets/90406808/141fd354-e2b0-4c33-b386-8caed2ab7c70)

Лайк!

2023-10-10 19:38 UTC, merged